### ISSUE TITLE
Bug Report: error compiling!!! wtf!

### ISSUE THREAD

**Issue by mayo78** [Erizur/FNF-DaveEngine#1]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

windows 64 bit

## What version of the game are you using? Look in the bottom left corner of the main menu.

latest commit

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.

i just cant comopike!

## Please describe your issue. Provide extensive detail and images if possible.

when i try to compile it gives me this error:

```
source/PlayState.hx:300: characters 12-24 : Type not found : VideoHandler
source/Character.hx:14: lines 14-770 : ... Defined in this class
source/Note.hx:273: characters 18-28 : Class<PlayState> has no field scrollType
```

**Comment by Erizur** [comment]
it's an issue with your version of hxcodec, please make sure youre using the haxelib from the [hxCodec git](https://github.com/polybiusproxy/hxCodec) instead of the haxelib version as it has not been updated for a long time now.

**Comment by imdumlol** [comment]
i still get the same thing

**Comment by imdumlol** [comment]
never mind
