### ISSUE TITLE
Enhancement: psych engine stuff support

### ISSUE THREAD

**Issue by lime360** [Erizur/FNF-DaveEngine#17]
## What is your suggestion, and why should it be implemented?
I want a support for Psych Engine's event system, modpacks and modcharts because It will make it easier for people who migrated from Psych to here

**Comment by ShadowMilky** [comment]
he already added modcharts in hscript
its just unfinished

**Comment by Erizur** [comment]
I'm not likely going to do this as this engine is not aiming to be like yoshi engine where you can port stuff from it to psych or viceversa, sorry.

**Comment by Erizur** [comment]
> he already added modcharts in hscript its just unfinished

its probably going to be unfinished for an indefinite time as i don't know how to continue from here and the script does not work, i'll see what i can do for now.

**Comment by ShadowMilky** [comment]
> > he already added modcharts in hscript its just unfinished
> 
> its probably going to be unfinished for an indefinite time as i don't know how to continue from here and the script does not work, i'll see what i can do for now.

me, that fixed the script thingy: :trollface:

**Comment by Erizur** [comment]
> me, that fixed the script thingy already: :trollface:

could you try adding it to the main engine as a pull request, i really need help with this lol
