### ISSUE TITLE
issue with hscripting.

### ISSUE THREAD

**Issue by REALHaydenGaming** [Erizur/FNF-DaveEngine#19]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
linux, porting a well respected mod on it.
## What version of the game are you using? Look in the bottom left corner of the main menu.
github commit
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
nope, compiling them is an issue.
## Please describe your issue. Provide extensive detail and images if possible.
source/HScriptTool.hx:84: characters 17-29 : hscript.Interp has no field errorHandler
source/HScriptTool.hx:132: characters 34-52 : { r : Dynamic, depth : Int } has extra field depth
source/HScriptTool.hx:132: characters 34-52 : For function argument 'value'

**Comment by MemeHoovy** [comment]
It’s based on Yoshicrafter engine Hscript, so I think you have to install yoshicrafters fork of Hscript
