### ISSUE TITLE
how to fix this compiling issue cause I'm dumb

### ISSUE THREAD

**Issue by NoSideYT** [Erizur/FNF-DaveEngine#20]
![chickfila](https://user-images.githubusercontent.com/109301694/201394299-487c2d09-ca46-4211-a1e7-bf06bc194255.png)

**Comment by DavidDXOfficial** [comment]
![image](https://user-images.githubusercontent.com/117064691/204567057-7821cd56-7a7f-4960-891c-b3203be6d153.png)
I get this instead when I compile the engine for the first time for some reason

**Comment by MemeHoovy** [comment]
> ![image](https://user-images.githubusercontent.com/117064691/204567057-7821cd56-7a7f-4960-891c-b3203be6d153.png) I get this instead when I compile the engine for the first time for some reason

haxelib git hxCodec https://github.com/polybiusproxy/hxCodec

**Comment by DavidDXOfficial** [comment]
> haxelib git hxCodec https://github.com/polybiusproxy/hxCodec

Thank ya for the solution, bro

**Comment by MemeHoovy** [comment]
your welcome

**Comment by Erizur** [comment]
Closed since its complete.
