### ISSUE TITLE
errors during compiling D:

### ISSUE THREAD

**Issue by jan-doez-animationz** [Erizur/FNF-DaveEngine#22]
here are the errors please heellppp D:
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodScriptClass.hx:60: characters 52-56 : polymod.hscript._internal.ErrorEx has no field line
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodScriptClass.hx:63: characters 87-91 : polymod.hscript._internal.ErrorEx has no field line
source/NGio.hx:12: characters 1-68 : io.newgrounds.objects.events.Result has no field or subtype GetCurrentVersionResult
source/NGio.hx:13: characters 1-61 : io.newgrounds.objects.events.Result has no field or subtype GetVersionResult
source/NGio.hx:47: characters 62-76 : io.newgrounds.Call<io.newgrounds.objects.events.GetCurrentVersionData> has no field addDataHandler (Suggestion: addStatusHandler)
source/NGio.hx:47: characters 104-127 : Type not found : GetCurrentVersionResult
source/NGio.hx:97: characters 25-39 : () -> Void should be Null<io.newgrounds.objects.events.Outcome<io.newgrounds.CallError> -> Void>
source/NGio.hx:97: characters 25-39 : ... For optional function argument 'callback'
source/NGio.hx:100: characters 30-45 : () -> Void should be Null<io.newgrounds.objects.events.Outcome<io.newgrounds.CallError> -> Void>
source/NGio.hx:100: characters 30-45 : ... For optional function argument 'callback'
source/NGio.hx:86: characters 25-34 : () -> Void should be Null<io.newgrounds.LoginOutcome -> Void>
source/NGio.hx:86: characters 25-34 : ... For optional function argument 'callback'
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodScriptClass.hx:366: characters 69-73 : polymod.hscript._internal.ErrorEx has no field line
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:73: characters 14-43 : polymod.hscript._internal.ErrorEx should be hscript.Error
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:73: characters 14-43 : ... For function argument 'e'
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:442: characters 16-41 : polymod.hscript._internal.ErrorEx should be hscript.Error
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:442: characters 16-41 : ... For function argument 'e'
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:450: characters 13-38 : polymod.hscript._internal.ErrorEx should be hscript.Error
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:450: characters 13-38 : ... For function argument 'e'
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:105: characters 13-40 : polymod.hscript._internal.ErrorEx should be hscript.Error
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:105: characters 13-40 : ... For function argument 'e'
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:483: characters 13-38 : polymod.hscript._internal.ErrorEx should be hscript.Error
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:483: characters 13-38 : ... For function argument 'e'

**Comment by MemeHoovy** [comment]
that's vanilla FNF you dunce

**Comment by jan-doez-animationz** [comment]
ohhh well then how do i unintall those things

**Comment by MemeHoovy** [comment]
well you shouldn't, and also make the issue on the vanilla FNF repo instead https://github.com/ninjamuffin99/Funkin

**Comment by jan-doez-animationz** [comment]
okay

**Comment by jan-doez-animationz** [comment]
wait then what do i do i just wanna compile dave engine

**Comment by MemeHoovy** [comment]
https://github.com/ninjamuffin99/Funkin#build-instructions

**Comment by MemeHoovy** [comment]
but use haxe 4.2.5

**Comment by jan-doez-animationz** [comment]
ohhh

**Comment by jan-doez-animationz** [comment]
whats the command i have like never done this stuff before

**Comment by MemeHoovy** [comment]
for building
`lime build windows`
for haxelib, just simply `haxelib`

**Comment by jan-doez-animationz** [comment]
> but use haxe 4.2.5

i am tho

**Comment by jan-doez-animationz** [comment]
i am so confuseddd

**Comment by Erizur** [comment]
closing since this repo is not the correct one.
