### ISSUE TITLE
Compiler error

### ISSUE THREAD

**Issue by DavidDXOfficial** [Erizur/FNF-DaveEngine#23]
Hello, I was recently getting compiler errors and can't fix them. Can anyone tell me how to fix this?

source/PlayState.hx:255: characters 12-24 : Type not found : VideoHandler
source/Character.hx:14: lines 14-770 : ... Defined in this class
source/HScriptTool.hx:84: characters 17-29 : hscript.Interp has no field errorHandler
source/HScriptTool.hx:132: characters 34-52 : { r : Dynamic, depth : Int } has extra field depth
source/HScriptTool.hx:132: characters 34-52 : ... For function argument 'value'
source/Note.hx:165: characters 18-28 : Class<PlayState> has no field scrollType

I have no clue why did this happen. I am using a Windows x86_64 host. If anyone came up with a solution, please tell me. I modified some stuff in PlayState of the engine for a mod and I ran into this issue.

**Comment by DavidDXOfficial** [comment]
I now get this
![image](https://user-images.githubusercontent.com/117064691/204566631-1006a9fc-45e2-443f-bd99-020c162ec69a.png)
 I fixed the issue of the hscript thingy

**Comment by MemeHoovy** [comment]
dawg, `haxelib git hxCodec https://github.com/polybiusproxy/hxCodec`

**Comment by MemeHoovy** [comment]
@DavidDXOfficial close this issue please

**Comment by DavidDXOfficial** [comment]
> 

Im gonna close it. Thanks for the solution again
