### ISSUE TITLE
how to use modcharts?????

### ISSUE THREAD

**Issue by imdumlol** [Erizur/FNF-DaveEngine#26]
can you use lua or no

**Comment by MemeHoovy** [comment]
you can't use lua because **it doesn't support lua you fucking dumbass**

**Comment by imdumlol** [comment]
oh ok

**Comment by imdumlol** [comment]
but how do i do them then?

**Comment by MemeHoovy** [comment]
the engine has no modchart support as far as I know

**Comment by imdumlol** [comment]
this was made of the vs Dave and Bambi 3.0 right? if so cheating, + all of the expunged songs have modcharts

**Comment by MemeHoovy** [comment]
erizur took them out

**Comment by imdumlol** [comment]
oh
