### ISSUE TITLE
Bug Report: Random characters in Subtitles

### ISSUE THREAD

**Issue by EnragedBambiOfficialCodes** [Erizur/FNF-DaveEngine#27]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

Windows (X64)

## What version of the game are you using? Look in the bottom left corner of the main menu.
DE 0.1.0(ALPHA)
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Nah I have no one
## Please describe your issue. Provide extensive detail and images if possible.
when I coded subtitles in a song, I found out that the subtitles went from random characters into a normal text. Is this normal or not?

**Comment by Erizur** [comment]
it is.
