### ISSUE TITLE
Enhancement: Mouse interaction in StoryMenuState

### ISSUE THREAD

**Issue by EnragedBambiOfficialCodes** [Erizur/FNF-DaveEngine#28]
## What is your suggestion, and why should it be implemented?

My suggestion is: Clickable weeks aka the Mouse interaction with the week score.
Reason: Idk.

**Comment by Erizur** [comment]
Sorry, no.

**Comment by EnragedBambiOfficialCodes** [comment]
> Sorry, no.

It's fine :)
