### ISSUE TITLE
hhhhhhhhhhhmmmmmmmmmmmmmmmm

### ISSUE THREAD

**Issue by imdumlol** [Erizur/FNF-DaveEngine#33]
source/PlayState.hx:255: characters 12-24 : Type not found : VideoHandler
source/Character.hx:14: lines 14-770 : ... Defined in this class
source/Note.hx:166: characters 18-28 : Class<PlayState> has no field scrollType
source/CompatWarningState.hx:31: characters 114-116 : flixel.util.FlxAxes should be Float
source/CompatWarningState.hx:31: characters 114-116 : ... For optional function argument 'ScrollX'
source/SelectLanguageState.hx:35: characters 113-115 : flixel.util.FlxAxes should be Float
source/SelectLanguageState.hx:35: characters 113-115 : ... For optional function argument 'ScrollX'

idk how to fix bruh

**Comment by imdumlol** [comment]
help?

**Comment by MemeHoovy** [comment]
use the git version of hxCodec & use an older version of flixel addons

**Comment by imdumlol** [comment]
what version of  flixel addons?

**Comment by MemeHoovy** [comment]
[2.11.0](https://lib.haxe.org/p/flixel-addons/2.11.0/)

**Comment by imdumlol** [comment]
it says it does not exist

**Comment by imdumlol** [comment]
that version

**Comment by MemeHoovy** [comment]
you did run this right?

`haxelib install flixel-addons 2.11.0`

**Comment by imdumlol** [comment]
worked thx

**Comment by MemeHoovy** [comment]
You’re welcome

**Comment by imdumlol** [comment]
now i get this ):

source/PauseSubState.hx:85: characters 113-115 : flixel.util.FlxAxes should be Float
source/PauseSubState.hx:85: characters 113-115 : ... For optional function argument 'ScrollX'
source/CompatWarningState.hx:31: characters 114-116 : flixel.util.FlxAxes should be Float
source/CompatWarningState.hx:31: characters 114-116 : ... For optional function argument 'ScrollX'
source/SelectLanguageState.hx:35: characters 113-115 : flixel.util.FlxAxes should be Float
source/SelectLanguageState.hx:35: characters 113-115 : ... For optional function argument 'ScrollX'

**Comment by imdumlol** [comment]
i did install flixel-addons + hxCodec

**Comment by MemeHoovy** [comment]
> now i get this ):
> 
> source/PauseSubState.hx:85: characters 113-115 : flixel.util.FlxAxes should be Float source/PauseSubState.hx:85: characters 113-115 : ... For optional function argument 'ScrollX' source/CompatWarningState.hx:31: characters 114-116 : flixel.util.FlxAxes should be Float source/CompatWarningState.hx:31: characters 114-116 : ... For optional function argument 'ScrollX' source/SelectLanguageState.hx:35: characters 113-115 : flixel.util.FlxAxes should be Float source/SelectLanguageState.hx:35: characters 113-115 : ... For optional function argument 'ScrollX'

I think I screwed up from a PR I made

**Comment by MemeHoovy** [comment]
https://github.com/Erizur/FNF-DaveEngine/commit/484e2bc6523f22a13252e56d4c87a044cf000740

**Comment by imdumlol** [comment]
wdym?

**Comment by MemeHoovy** [comment]
I’ll fix it when I get back :P

**Comment by imdumlol** [comment]
ok

**Comment by imdumlol** [comment]
did you fix it yet? or can you?

**Comment by MemeHoovy** [comment]
I forgot

**Comment by imdumlol** [comment]
can you fix now plz (i really want to make a DnB mod)

**Comment by MemeHoovy** [comment]
alright

**Comment by imdumlol** [comment]
i still get this 


source/PlayState.hx:255: characters 12-24 : Type not found : VideoHandler
source/Character.hx:14: lines 14-770 : ... Defined in this class
source/Note.hx:166: characters 18-28 : Class<PlayState> has no field scrollType

**Comment by imdumlol** [comment]
hello?

**Comment by MemeHoovy** [comment]
> i still get this
> 
> source/PlayState.hx:255: characters 12-24 : Type not found : VideoHandler source/Character.hx:14: lines 14-770 : ... Defined in this class source/Note.hx:166: characters 18-28 : Class has no field scrollType

use the git version of hxCodec

**Comment by imdumlol** [comment]
ah ok

**Comment by imdumlol** [comment]
can you link it?

**Comment by imdumlol** [comment]
i get the same darn thing

**Comment by imdumlol** [comment]
is there a version i need?

**Comment by MemeHoovy** [comment]
idk what else to say then
