### ISSUE TITLE
Bug Report: compile ):

### ISSUE THREAD

**Issue by imdumlol** [Erizur/FNF-DaveEngine#43]
source/PlayState.hx:160: characters [12](https://github.com/Erizur/FNF-DaveEngine/actions/runs/4127835145/jobs/7131528074#step:6:13)-24 : Type not found : VideoHandler
source/FreeplayState.hx:23: lines 23-563 : ... Defined in this class
source/HScriptTool.hx:177: characters 18-30 : Class<PlayState> has no field canRunScript
source/HScriptTool.hx:187: characters 18-30 : Class<PlayState> has no field canRunScript
source/HScriptTool.hx:30: characters 18-30 : Class<PlayState> has no field canRunScript
source/Note.hx:156: characters 18-28 : Class<PlayState> has no field scrollType

**Comment by MemeHovy** [comment]
please use the git version of hxCodec

**Comment by MemeHovy** [comment]
actually I'm getting sick of seeing issues like this so I'm gonna do something drastic

**Comment by imdumlol** [comment]
i am

**Comment by MemeHovy** [comment]
oh wait, I think it might be because of the new changes in hxCodec

**Comment by MemeHovy** [comment]
or me stupidly removing an import

**Comment by JwallsRBLX** [comment]
> oh wait, I think it might be because of the new changes in hxCodec

I did that and it still give me the error
