### ISSUE TITLE
how do you even use the engine how do u port it?

### ISSUE THREAD

**Issue by fieroiscool** [Erizur/FNF-DaveEngine#47]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by fieroiscool** [comment]
please tell me how to use it

**Comment by Erizur** [comment]
it has no modding support, its a modified version of kade engine, so you will have to learn haxe and do all the work yourself.
