### ISSUE TITLE
Future of the Engine notice

### ISSUE THREAD

**Issue by Erizur** [Erizur/FNF-DaveEngine#48]
**Hi everybody!**

By everybody I mean people that is still using the engine. I know that things have been very slow during the last couple of months relating to the development of this silly project i made in order to make people interested in making their own dnb fanmods with the (probably official, who knows) engine of the original mod. Sadly, my lack of interest, the upcoming dave & bambi update, school, and some other projects i'm also working on, have made development of this engine impossible and it's currently on an abandoned state. Unless someone else is interested on mantaining this project, adding modding support and the missing features I was planning on adding to this engine, I would call this project finished and archived for good.

If someone wants to mantain the engine, contact me on Discord (Erizur#7498) for more details, if you're up to the task, i'll most likely give you repo access to do all the stuff this engine needs.

If that's not the case, I recommend all the people that are currently using this engine to move to other engines, here are some:

- [Psych Engine](https://github.com/ShadowMario/FNF-PsychEngine)
- [OS Engine (Although this one is archived)](https://github.com/notweuz/FNF-OSEngine)
- [Codename Engine (Still on a beta state but overall solid enough)](https://github.com/YoshiCrafter29/CodenameEngine)

Don't think this is the last time I'll work on something related to fnf engines, I'm a contributor on a new engine created by one of my friends that is being created for the ease of modding specific parts of the game. [Check it out!](https://github.com/benjaminpants/Funkin-Strawberry)

That's everything, thanks for all the support this engine has gotten. Goodbye!

**Comment by MemeHovy** [comment]
gonna close due to there now being a maintainer
