### ISSUE TITLE
Shaders

### ISSUE THREAD

**Issue by TBoity4** [Erizur/FNF-DaveEngine#50]
So I did something stupid and activated shaders by mistake and I have no idea how to actually turn them off.
I've tried deleting my save data and that didn't work. Pretty much my only option is to remove the shader.hx class and remove every trace of it. But I'm too lazy to do allat so is there another way of removing shaders?

**Comment by MemeHovy** [comment]
remove the `SHADERS_ENABLED` in project.xml to disable them

**Comment by TBoity4** [comment]
It works les go
