### ISSUE TITLE
winning icons.

### ISSUE THREAD

**Issue by tomasxd12** [Erizur/FNF-DaveEngine#52]
#### Please check for duplicates or similar issues before creating this issue.
there are none :P
## What is your suggestion, and why should it be implemented?
due well i cant find any one in the internet soo idk like maybe implemented by default? if its by default or in the internet, close this issue. OR JUST ADD THEM IDK also when LUA SUPPORT?

**Comment by tomasxd12** [comment]
Well, somone put help wanted on this issue

**Comment by MemeHovy** [comment]
later

**Comment by MemeHovy** [comment]
I'll consider adding winning icons

**Comment by tomasxd12** [comment]
thank you dude

**Comment by tomasxd12** [comment]
adding them was it

**Comment by MemeHovy** [comment]
I’ll do it when I’m home either tomorrow or on Monday

**Comment by tomasxd12** [comment]
k see ya

**Comment by tomasxd12** [comment]
this issue is 2 weeks old now

**Comment by MemeHovy** [comment]
> this issue is 2 weeks old now

I’m not home until the 25th

**Comment by tomasxd12** [comment]
oh darn

**Comment by tomasxd12** [comment]
alright

**Comment by Erizur** [comment]
Can’t implement unless I ask people from other engines to grab their winning icons and assets. Will close because there’s no solution for now.

**Comment by MemeHovy** [comment]
> Can’t implement unless I ask people from other engines to grab their winning icons and assets (I am not really an artist).
> Will close because there’s no solution for now.

alright
