### ISSUE TITLE
neardeath icons boiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii

### ISSUE THREAD

**Issue by tomasxd12** [Erizur/FNF-DaveEngine#54]
#### Please check for duplicates or similar issues before creating this issue.
nope
## What is your suggestion, and why should it be implemented?
Neardeath icons. Opposite as the winning icons as in #52 and well, dont expect alot. Bet if this is planned!

**Comment by tomasxd12** [comment]
fr im gonna sleep, goodbye! so i expect the messages from now on being like 2 hours.

**Comment by MemeHovy** [comment]
already a thing
