### ISSUE TITLE
missing documentation crap

### ISSUE THREAD

**Issue by tomasxd12** [Erizur/FNF-DaveEngine#55]
#### Please check for duplicates or similar issues before creating this issue.
none
## What is your suggestion, and why should it be implemented?
fr make the discussions public and the wiki too so idk

**Comment by MemeHovy** [comment]
I can’t do anything about the discussions, since that’s up to @Erizur but I can help make documentation

**Comment by tomasxd12** [comment]
alright, soo

**Comment by tomasxd12** [comment]
make some crappy steps in readme.md i guess and closed when youre done?

**Comment by MemeHovy** [comment]
yea, and the wiki too

**Comment by tomasxd12** [comment]
okay

**Comment by Erizur** [comment]
Once modding support gets fully implemented, I will most likely create documentation, if you want to add/modify stuff you will have to do it by editing the source code.

**Comment by MemeHovy** [comment]
> Once modding support gets fully implemented, I will most likely create documentation.
> 
> If you want to add/modify stuff to the engine you will have to do it by editing the source code. Closing this for now and will reopen once I can manage this correctly.

I could help with that tho
