### ISSUE TITLE
First stable milestone issue: crappy Psych engine chart compatiblity.

### ISSUE THREAD

**Issue by tomasxd12** [Erizur/FNF-DaveEngine#56]
#### Please check for duplicates or similar issues before creating this issue
no
## What is your suggestion, and why should it be implemented?
Its because im doing a mod that is this link: (https://gamebanana.com/mods/450679) and i want to be running here. The code is psych engine, due i started it on 0.6.3.

**Comment by MemeHovy** [comment]
seems interesting, alright, I’ll owe up to it

**Comment by tomasxd12** [comment]
yes to those ppl that didint click on that, its an suss tongus rechart made by me. In development anyways.

**Comment by tomasxd12** [comment]
uh whatever ill try to port it somehow alright?

**Comment by MemeHovy** [comment]
alright, I’ll add support when I can

**Comment by tomasxd12** [comment]
k ill get to porting this

**Comment by MemeHovy** [comment]
okay 👍

**Comment by tomasxd12** [comment]
hmm ima replace the plugins with the psych ones

**Comment by tomasxd12** [comment]
i may have corrupted some crap oops

**Comment by tomasxd12** [comment]
idk

**Comment by tomasxd12** [comment]
gosh this is gonna take forever

**Comment by tomasxd12** [comment]
i broke the zip .-. gotta download again

**Comment by tomasxd12** [comment]
nope fixed lets get to this

**Comment by tomasxd12** [comment]
alright ima upload to gamebanana, ima give credits.

**Comment by MemeHovy** [comment]
okay

**Comment by Erizur** [comment]
Will close this.
I do not want any type of psych engine (versions 0.6+) compatibility since they redid their charting system and making it compatible with the old kade engine and base fnf charts is not possible and will add a ton of unnecessary stuff to the mod. I might change my opinion on this later, but for now, no.

**Comment by MemeHovy** [comment]
> Will close this.
> I do not want any type of psych engine (versions 0.6+) compatibility since they redid their charting system and making it compatible with the old kade engine and base fnf charts is not possible and will add a ton of unnecessary stuff to the engine. I might change my opinion on this later, but for now, no.

noted

**Comment by tomasxd12** [comment]
hm

**Comment by MemeHovy** [comment]
hey @tomasxd12 I can attempt this in my own fork if you like 👍 
since I’ll use it to add features Erizur won’t add or won’t let me add

**Comment by tomasxd12** [comment]
sure dude

**Comment by tomasxd12** [comment]
fr ill work on that alright
im not good but ill try

**Comment by tomasxd12** [comment]
alright ill get the repo im planning it being kade engine or idk?

**Comment by tomasxd12** [comment]
change the source code if you want tho

**Comment by MemeHovy** [comment]
alright

**Comment by tomasxd12** [comment]
@MemeHovy i got the engine were gonna use: https://gamebanana.com/mods/291518 ke improved 1.5.4

**Comment by MemeHovy** [comment]
> @MemeHovy i got the engine were gonna use: https://gamebanana.com/mods/291518 ke improved or psych engine and ‘borrow’ the winning icon code from OS Engine or idk

okay 👍
