### ISSUE TITLE
Porting into Kade Engine 1.4.2? forget this

### ISSUE THREAD

**Issue by tomasxd12** [Erizur/FNF-DaveEngine#57]
Alright, this is the start. Any tips?, for now im adding note splash.. uh i was editing this comment.. and closed :P

**Comment by MemeHovy** [comment]
don’t ask us on the issue tracker for this, wait until the discussions are made, because that is not what the issue tracker is for

**Comment by tomasxd12** [comment]
closed

**Comment by JokeBambi** [comment]
to answer ur question: moldy does not like ke 1.2.1 and up because it has anti mash so no
