### ISSUE TITLE
Bug Report: Crash

### ISSUE THREAD

**Issue by kiruhasas22** [Erizur/FNF-DaveEngine#60]
(Windows)

![image](https://github.com/Erizur/FNF-DaveEngine/assets/120410258/9ce02a57-0d81-4726-aced-825e2ed73699)

**Comment by MemeHovy** [comment]
I'm working on revamping BGSprite so rn it crashes, but I'll have it fixed soon

**Comment by kiruhasas22** [comment]
> I'm working on revamping BGSprite so rn it crashes, but I'll have it fixed soon

ok
