### ISSUE TITLE
Bug Report: numscore

### ISSUE THREAD

**Issue by kiruhasas22** [Erizur/FNF-DaveEngine#61]
(windows)
when it shows 10,20,30 etc it shows 0 and if 11 etc it shows 1 etc

**Comment by kiruhasas22** [comment]
and also in the week 7 stage there are HaxeFlixel icons in the background

**Comment by kiruhasas22** [comment]
and at 6 week no pixel arrows

**Comment by kiruhasas22** [comment]
> and at 6 week no pixel arrows

the same can be said about numscore

**Comment by MemeHovy** [comment]
I'm aware of that, I'm gonna get to them eventually
