### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by JokeBambi** [Erizur/FNF-DaveEngine#65]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
windows 10 x64 bit

## What version of the game are you using? Look in the bottom left corner of the main menu.
dnb 3.0b

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
no

## Please describe your issue. Provide extensive detail and images if possible.
source/PlayState.hx:292: characters 12-24 : Type not found : VideoHandler
source/LoadingState.hx:18: lines 18-226 : ... Defined in this class
source/StoryMenuState.hx:260: characters 17-29 : Type not found : VideoHandler
source/CompatWarningState.hx:27: characters 72-73 : Int should be flixel.util.FlxAxes
source/CompatWarningState.hx:27: characters 72-73 : ... For optional function argument 'repeatAxes'
source/Note.hx:339: characters 18-28 : Class<PlayState> has no field scrollType
source/SelectLanguageState.hx:34: characters 70-71 : Int should be flixel.util.FlxAxes
source/SelectLanguageState.hx:34: characters 70-71 : ... For optional function argument 'repeatAxes'

nothing edited

**Comment by JokeBambi** [comment]
nvm people will probably not respond so god dang it

**Comment by MemeHovy** [comment]
don’t make issues about the mod here since this is more for the engine instead

**Comment by JokeBambi** [comment]
> please don’t make issues about the mod here since this is more for the engine instead

well, its literally the same thing. it puts the same error

**Comment by MemeHovy** [comment]
> > please don’t make issues about the mod here since this is more for the engine instead
> 
> well, its literally the same thing. it puts the same error

the code for the engine has been modified a lot from DNB

**Comment by JokeBambi** [comment]
makes sense, ill try to compile from the engine

**Comment by MemeHovy** [comment]
> makes sense, ill try to compile from the engine

alright

**Comment by JokeBambi** [comment]
oh the engine works ok i was gonna post a error of why i couldnt install hscript and then saw there was a github res for it so i git from that and it worked

**Comment by MemeHovy** [comment]
> oh the engine works ok i was gonna post a error of why i couldnt install hscript and then saw there was a github res for it so i git from that and it worked

👍🏻
