### ISSUE TITLE
subtitles

### ISSUE THREAD

**Issue by JokeBambi** [Erizur/FNF-DaveEngine#66]
## What is your suggestion, and why should it be implemented?
subtitles, like dave and bambi this would be useful for people who doesnt know what the characters are saying.

**Comment by MemeHovy** [comment]
for what?

**Comment by MemeHovy** [comment]
I mean, I see it could be used for week 7, so I might reimplement it for that

**Comment by JokeBambi** [comment]
thanks

**Comment by JokeBambi** [comment]
it could also be for winter horrorland

**Comment by MemeHovy** [comment]
> thanks

np

> it could also be for winter horrorland

good idea

**Comment by JokeBambi** [comment]
now a pull request
