### ISSUE TITLE
Bug Report: compiling issue

### ISSUE THREAD

**Issue by Darkdizzyyy** [Erizur/FNF-DaveEngine#69]
source/Main.hx:101: characters 24-61 : Type not found : flixel.addons.plugin.ScreenShotPlugin

is there something i need to install??

**Comment by Darkdizzyyy** [comment]
NVM LMAO I JUST NEEDED TO REPLACE "FlxG.plugins.add(new flixel.addons.plugin.ScreenShotPlugin());" WITH "flixel.FlxG.plugins.add(new screenshotplugin.ScreenShotPlugin());"

**Comment by MemeHovy** [comment]
you didn't update to the latest version is why
