### ISSUE TITLE
What is the code that installs this in cmd?

### ISSUE THREAD

**Issue by pablowolfgamerbr** [Erizur/FNF-DaveEngine#72]
C:\Users\???\Desktop\FNF-DaveEngine-main>lime test windows
Error: Could not find haxelib "hscript-improved", does it need to be installed?

**Comment by MemeHovy** [comment]
`haxelib git hscript-improved https://github.com/FNF-CNE-Devs/hscript-improved`
Erizur didn’t include it in the setup instructions for some reason
