### ISSUE TITLE
Bug rEPOrt: test failed

### ISSUE THREAD

**Issue by baldi2** [Erizur/FNF-DaveEngine#73]
i am using
windows x86_64

i dont know what i am using version
i dont know
reproduceing bug
install haxe 4.3.3
issue
help when i do lime test windows (YES I DID hhscript improved) this happens

C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/system/System.hx:817: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/graphics/opengl/GL.hx:2638: characters 28-34 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/ArrayBufferView.hx:403: characters 28-34 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/graphics/PixelFormat.hx:6: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/_internal/graphics/ImageDataUtil.hx:1751: characters 28-34 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/net/curl/CURLCode.hx:4: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/net/curl/CURLMultiCode.hx:4: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/net/HTTPRequestMethod.hx:3: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/graphics/RenderContextType.hx:6: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/LogLevel.hx:3: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/graphics/cairo/CairoFilter.hx:4: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/AssetType.hx:3: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/ui/KeyCode.hx:6: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/graphics/cairo/CairoAntialias.hx:4: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/graphics/cairo/CairoHintMetrics.hx:4: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/graphics/cairo/CairoHintStyle.hx:4: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/graphics/cairo/CairoOperator.hx:4: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/graphics/cairo/CairoExtend.hx:4: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/ui/GamepadAxis.hx:3: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/ui/GamepadButton.hx:3: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/_internal/backend/native/NativeWindow.hx:668: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/_internal/backend/native/NativeWindow.hx:685: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/graphics/cairo/CairoFormat.hx:4: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/ui/MouseButton.hx:3: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/_internal/backend/native/NativeApplication.hx:636: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/_internal/backend/native/NativeApplication.hx:657: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/_internal/backend/native/NativeApplication.hx:679: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/_internal/backend/native/NativeApplication.hx:707: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/_internal/backend/native/NativeApplication.hx:741: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/_internal/backend/native/NativeApplication.hx:773: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/_internal/backend/native/NativeApplication.hx:806: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/_internal/backend/native/NativeApplication.hx:829: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/_internal/backend/native/NativeApplication.hx:859: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/_internal/backend/native/NativeApplication.hx:888: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/_internal/backend/native/NativeApplication.hx:923: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/_internal/backend/native/NativeApplication.hx:955: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/Int16Array.hx:151: characters 16-24 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/Int16Array.hx:158: characters 16-24 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/Float64Array.hx:151: characters 16-24 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/utils/Float64Array.hx:158: characters 16-24 : Warning : (WDeprecated) `@:extern` is deprecated in favor of `extern`
its too long so i have ot split it

**Comment by baldi2** [comment]
do i update all my libraries

**Comment by MemeHovy** [comment]
> do i update all my libraries

yes, that's what I just told you

**Comment by baldi2** [comment]
literally the same issue, i updated all my libraries and haxelib, all up to date

**Comment by baldi2** [comment]
also i thought it was haxe 4.3.3?

**Comment by baldi2** [comment]
ok this worked for the dave engine, but not for the 3.0 archived/extra keys source.

**Comment by MemeHovy** [comment]
> ok this worked for the dave engine, but not for the 3.0 archived/extra keys source.

cuz not all of them are compatible because they were made before haxe 4.3
look this isn’t the place to keep further discussing this issue based on separate repos, I suggest you seek tutorials on how to fix these issues since they’re documented almost everywhere now
