### ISSUE TITLE
Bug Report: videohandler, sound, writing, private field id, and public as lime app Imodule.

### ISSUE THREAD

**Issue by baldi2** [Erizur/FNF-DaveEngine#74]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows (`x86_64`)

## What version of the game are you using? Look in the bottom left corner of the main menu.
https://github.com/BemboLikePizza/VsDave

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
1: Install Haxe 4.2.5
2: Upgrade all your libraries
3: lime test windows
## Please describe your issue. Provide extensive detail and images if possible.
Checking actuate
Checking colyseus
Checking colyseus-websocket
Checking discord_rpc
discord_rpc was updated
Checking extension-webm
Reset changes to extension-webm Git repo so we can pull latest version [y/n/a] ? y
extension-webm was updated
Checking flixel
Checking flixel-addons
Checking flixel-demos
Checking flixel-screenshot-plugin
flixel-screenshot-plugin was updated
Checking flixel-templates
Checking flixel-tools
Checking flixel-ui
Checking flxanimate
flxanimate was updated
Checking haxelib
Checking hmm
Checking hscript
Checking hscript-improved
hscript-improved was updated
Checking HtmlParser
Checking hxCodec
fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths

Updated it, lime test windows and then this.

C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/net/curl/CURL.hx:172: characters 15-36 : Cannot access field or identifier length for writing
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/net/curl/CURL.hx:174: characters 15-41 : Cannot access field or identifier length for writing
source/PlayState.hx:170: characters 20-28 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:171: characters 27-35 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/PlayState.hx:297: characters 12-24 : Type not found : VideoHandler
source/LoadingState.hx:16: lines 16-227 : ... Defined in this class
source/StoryMenuState.hx:260: characters 17-29 : Type not found : VideoHandler
source/MathGameState.hx:26: characters 17-25 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/MathGameState.hx:26: characters 32-40 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/MathGameState.hx:44: characters 20-28 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/MathGameState.hx:332: characters 20-28 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/MainMenuState.hx:300: characters 20-28 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/MainMenuState.hx:300: characters 35-43 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/MusicPlayerState.hx:34: characters 16-24 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/MusicPlayerState.hx:320: characters 23-31 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/MusicPlayerState.hx:324: characters 23-31 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/FreeplayState.hx:830: characters 18-26 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/TerminalState.hx:33: characters 23-31 : Warning : flixel.system.FlxSound was moved to flixel.sound.FlxSound
source/Note.hx:354: characters 18-28 : Class<PlayState> has no field scrollType
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/graphics/opengl/GL.hx:2597: characters 49-51 : Cannot access private field id
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/app/Module.hx:29: characters 27-49 : Field __unregisterLimeModule should be public as requested by lime.app.IModule
C:/HaxeToolkit/haxe/lib/lime/8,0,1/src/lime/app/Module.hx:27: characters 27-47 : Field __registerLimeModule should be public as requested by lime.app.IModule
C:/HaxeToolkit/haxe/lib/openfl/9,3,2/src/openfl/display/Stage.hx:3395: characters 34-56 : Field __unregisterLimeModule should be public as requested by lime.app.IModule
C:/HaxeToolkit/haxe/lib/openfl/9,3,2/src/openfl/display/Stage.hx:3176: characters 34-54 : Field __registerLimeModule should be public as requested by lime.app.IModule

**Comment by baldi2** [comment]
uuuuuuuuuukjikjikjikjikjikjikjikjikjikjikjikujdrfedresfg bvhnuiiiiiiiiiiiiiiiiiiiiiiiiii mmmmmmmmmmmmmmmmmmmmmmmmmnkn

**Comment by MemeHovy** [comment]
you did not update lime

**Comment by MemeHovy** [comment]
also, I can clearly tell you did NOT update all your libraries

**Comment by baldi2** [comment]
i just used haxelib upgrade

**Comment by baldi2** [comment]
left is source/PlayState.hx:297: characters 12-24 : Type not found : VideoHandler
source/LoadingState.hx:16: lines 16-227 : ... Defined in this class
source/StoryMenuState.hx:260: characters 17-29 : Type not found : VideoHandler
source/Note.hx:354: characters 18-28 : Class<PlayState> has no field scrollType

(the others are warnings)

**Comment by baldi2** [comment]
haxelib list:
actuate: 1.8.9 [1.9.0]
colyseus-websocket: 1.0.7 1.0.12 [1.0.13]
colyseus: 0.14.9 [0.15.2]
discord-rpc: [1.0.0]
discord_rpc: [git]
extension-webm: [git]
flixel-addons: 2.11.0 3.0.2 [3.2.1]
flixel-demos: 2.9.0 [3.1.0]
flixel-screenshot-plugin: 1.5.0 [git]
flixel-templates: [2.6.6]
flixel-tools: [1.5.1]
flixel-ui: 2.4.0 [2.5.0]
flixel: 4.11.0 5.2.2 [5.5.0]
flxanimate: [git]
haxelib: 4.0.3 [4.1.0]
hmm: [3.1.0]
hscript-improved: [git]
hscript: [2.5.0]
HtmlParser: [3.3.2]
hxCodec: 2.5.1 [3.0.2]
hxcpp-debug-server: [1.2.4]
hxcpp: 4.2.1 [4.3.2]
lime-samples: [7.0.0]
lime: 8.0.0 8.0.1 [8.1.1]
linc_luajit: [git]
markdown: [1.1.2]
newgrounds: 2.0.0 [2.0.2]
openfl: 9.2.0 9.2.1 [9.3.2]
polymod: 1.6.0 [git]
SScript: 6.1.80 7.0.0 7.7.0 [8.1.6]
thx.core: [0.44.0]
thx.semver: [0.2.2]
tink_await: [0.6.0]
tink_core: [2.1.1]
tink_macro: [1.0.3]
tink_priority: [0.1.4]
tink_stringly: [0.6.0]
tink_syntaxhub: [0.6.1]
tink_url: [0.5.0]
tjson: [1.4.0]
utest: [1.13.2]

**Comment by MemeHovy** [comment]
> left is source/PlayState.hx:297: characters 12-24 : Type not found : VideoHandler source/LoadingState.hx:16: lines 16-227 : ... Defined in this class source/StoryMenuState.hx:260: characters 17-29 : Type not found : VideoHandler source/Note.hx:354: characters 18-28 : Class has no field scrollType
> 
> (the others are warnings)

update the engine
