### ISSUE TITLE
help Compiling 

### ISSUE THREAD

**Issue by thegamenig** [Erizur/FNF-DaveEngine#76]
C:\Users\JD\Downloads\FNF-DaveEngine-main\FNF-DaveEngine-main>lime build windows -releaseC:/Users/JD/remkdir ~/haxelib && haxelib setup ~/haxelib/hscript-improved/git/hscript/macros/Utils.hx:195: characters 9-12 : Identifier 'EIs' is not part of haxe.macro.ExprDef (Suggestion: EIf)C:/Users/JD/remkdir ~/haxelib && haxelib setup ~/haxelib/hscript-improved/git/hscript/macros/Utils.hx:195: characters 9-18 : Unrecognized pattern: EIs(e, t)C:/Users/JD/remkdir ~/haxelib && haxelib setup ~/haxelib/hscript-improved/git/hscript/macros/ClassExtendMacro.hx:41: characters 10-20 : haxe.macro.ClassType has no field isAbstractC:/Users/JD/remkdir ~/haxelib && haxelib setup ~/haxelib/hscript-improved/git/hscript/macros/ClassExtendMacro.hx:260: characters 20-25 : Too many argumentsC:/Users/JD/remkdir ~/haxelib && haxelib setup ~/haxelib/flixel/4,8,1/flixel/graphics/tile/FlxDrawBaseItem.hx:9: characters 8-32 : Type not found : openfl.display.TilesheetC:/Users/JD/remkdir ~/haxelib && haxelib setup ~/haxelib/flixel/4,8,1/flixel/graphics/tile/FlxDrawTilesItem.hx:10: characters 8-32 : Type not found : openfl.display.TilesheetC:/Users/JD/remkdir ~/haxelib && haxelib setup ~/haxelib/flixel/4,8,1/flixel/graphics/FlxGraphic.hx:15: characters 8-32 : Type not found : openfl.display.Tilesheetsource/Main.hx:24: character 1 : Build failure

**Comment by thegamenig** [comment]
> C:\Users\JD\Downloads\FNF-DaveEngine-main\FNF-DaveEngine-main>lime build windows -releaseC:/Users/JD/remkdir ~/haxelib && haxelib setup ~/haxelib/hscript-improved/git/hscript/macros/Utils.hx:195: characters 9-12 : Identifier 'EIs' is not part of haxe.macro.ExprDef (Suggestion: EIf)C:/Users/JD/remkdir ~/haxelib && haxelib setup ~/haxelib/hscript-improved/git/hscript/macros/Utils.hx:195: characters 9-18 : Unrecognized pattern: EIs(e, t)C:/Users/JD/remkdir ~/haxelib && haxelib setup ~/haxelib/hscript-improved/git/hscript/macros/ClassExtendMacro.hx:41: characters 10-20 : haxe.macro.ClassType has no field isAbstractC:/Users/JD/remkdir ~/haxelib && haxelib setup ~/haxelib/hscript-improved/git/hscript/macros/ClassExtendMacro.hx:260: characters 20-25 : Too many argumentsC:/Users/JD/remkdir ~/haxelib && haxelib setup ~/haxelib/flixel/4,8,1/flixel/graphics/tile/FlxDrawBaseItem.hx:9: characters 8-32 : Type not found : openfl.display.TilesheetC:/Users/JD/remkdir ~/haxelib && haxelib setup ~/haxelib/flixel/4,8,1/flixel/graphics/tile/FlxDrawTilesItem.hx:10: characters 8-32 : Type not found : openfl.display.TilesheetC:/Users/JD/remkdir ~/haxelib && haxelib setup ~/haxelib/flixel/4,8,1/flixel/graphics/FlxGraphic.hx:15: characters 8-32 : Type not found : openfl.display.Tilesheetsource/Main.hx:24: character 1 : Build failure

**Comment by moxie-coder** [comment]
this will be fixed in future versions

**Comment by thegamenig** [comment]
Ok?
